### ISSUE TITLE
N64 USB Controller to my chromebook 

### ISSUE THREAD

**Issue by SlyYoung33** [SukkoPera/N64PadForArduino#1]
I had bought an N64 USB Controller for my Chromebook couple of days ago as I try to input the USB, nothing happened and I needed help. I wanted to play some N64 games from the past with the new controller and not play them on the keyboard.

**Comment by SukkoPera** [comment]
This project is for reading real N64 pads through an Arduino, which can somehow be used to make them USB. If you bought a N64-alike pad that is USB to begin with, this cannot be used in any way with that.
