### ISSUE TITLE
GCPadDump shows nothing

### ISSUE THREAD

**Issue by ARIVERDERCHI** [SukkoPera/N64PadForArduino#3]
Hi, 

Thanks for your work on this project.

I tried to use the GCPadDump with several Arduino uno's and one nano, and haven't gotten any of them to work as expected: nothing gets shown in serial monitor, even though im pressing buttons and moving joysticks on my original gamecube controller.

I tried a 1k and 10k ohm between data and 3.3V, nothing changed. I checked all different grounds, 3 , 4 and 7 none of them changed anything either. 

I probed with a multimeter the inside of the controller to make sure the 3.3V and GND pins were going through and seated properly, which they where.

Any tips? I guess the next step would be to buy an oscilloscope...

Thanks!

**Comment by ARIVERDERCHI** [comment]
![image](https://user-images.githubusercontent.com/40579020/167621633-5dd86037-c858-4417-a41e-d24538f91b07.jpeg)

![image](https://user-images.githubusercontent.com/40579020/167621722-0fddee56-e12b-4216-81f6-0404e42607d0.jpeg)

**Comment by SukkoPera** [comment]
You seem to be using pin 2, but [the library has pin 3 enabled by default on the Uno](https://github.com/SukkoPera/N64PadForArduino/blob/master/src/protocol/pinconfig.h#L36). Did you edit the pinconfig.h file to change that?

**Comment by ARIVERDERCHI** [comment]
Ah ok thank you, now I see some values :) 

I was using pin 2 because it was written in the comments of the GCPadDump. 

Now it only shows gibberish though, says I'm pressing down buttons when I'm not, and values don't change when I move sticks. I forgot to switch 3.3V with 5V for my original controller (before I was testing this other controller that only had the 5v pin). 

Do you know if the controller board has over voltage protection on the 3.3V pin? Could i have broken the controller board by giving 5V on the 3.3V pin?

Thanks!

**Comment by SukkoPera** [comment]
It's possible that you broke the controller but it's very unlikely. Make sure to connect both ground pins and use a 1k pull-up.

I know I should update the docs...

**Comment by SukkoPera** [comment]
Closing since there was no update in a long time.
