### ISSUE TITLE
[Confirmation] Library not working with the 3.3v 8Mhz Pro Micro

### ISSUE THREAD

**Issue by capitaineflam25** [SukkoPera/N64PadForArduino#5]
Just a confirmation : the signal is not decoded at all with a 3.3v 8Mhz Pro Micro.

So i'm using a 5V 16Mhz Pro Micro with [a cheap and small 5V to 3.3V voltage regulator](https://fr.aliexpress.com/item/1005002829381037.html) and it works perfectly.

**Comment by SukkoPera** [comment]
Thanks for the report. Did you try removing a few NOPs as indicated?

**Comment by capitaineflam25** [comment]
Ah sorry, i've tested the code as is.

**Comment by SukkoPera** [comment]
Removing a few NOPs might make it work, but some testing with a scope/LA should be done. One day ;).

**Comment by SukkoPera** [comment]
Closing since there was no update in a long time.
